### ISSUE TITLE
Update Architectury Dep

### ISSUE THREAD

**Issue by FaNt4zMa** [kiber-pacan/shelf-mod-arch#3]
Architectury API just got updated and your mod doesn't work with the new version.
![image](https://github.com/user-attachments/assets/76131a2d-5d3a-4777-aaf0-ee8d37074f5c)
Thanks

**Comment by kiber-pacan** [comment]
currently working on big update, soon to be released

**Comment by FaNt4zMa** [comment]
Gotcha, in the meantime I just rolled back Architectury API and other mods relying on its most recent version. Waiting for update :)
