### ISSUE TITLE
Unable to using an 1.21.1 Version

### ISSUE THREAD

**Issue by suerion** [kiber-pacan/shelf-mod-arch#4]
Hey, i had tested all Version of Shelf for fabric, but all versions on Modrinth are not working on 1.21.1

tried also the latest 1.4 version.

please add compatibility with 1.21.1, Thanks

![image](https://github.com/user-attachments/assets/7013d7e1-e95f-490e-be71-1c9343cb6910)
![image](https://github.com/user-attachments/assets/84c0a71b-59d6-4fde-b159-90a4bc666ecc)

**Comment by kiber-pacan** [comment]
fixed

**Comment by suerion** [comment]
![image](https://github.com/user-attachments/assets/e94880e6-4d75-4b19-9858-3975d2ad9857)

On modrinth there is a version, that not work on 1.21.1, on Curseforge, there is the only released verion for 1.21.1 only 1.1 and not 1.4, hope we could use it soon :) thanks for trying to fix
https://www.curseforge.com/minecraft/mc-mods/shelf-mod/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=4

**Comment by suerion** [comment]
@kiber-pacan

**Comment by kiber-pacan** [comment]
later

**Comment by kiber-pacan** [comment]
give me 6 months
